
using System.Globalization;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Tree.ObjectModel;
using Tree.Properties;

namespace Tree.Tests
{
   
    [TestClass]
    public static class Seed
    {
        [AssemblyInitialize]
        public static void CoverAutogeneratedCode(TestContext context)
        {
            var settings = Settings.Default;
            Assert.IsNotNull(settings);

            var resources = new Resources();
            
            Resources.Culture = new CultureInfo("en-US");
            var culture = Resources.Culture;

            var rm = Resources.ResourceManager;
        }

        public static Node GetSampleTree()
        {
            var node = new Node();
            node.Name("root")
                .AddChild().Name("COMP 1")
                    .AddChild().Name("PROD 1 von COMP 1")
                        .AddChild().Name("REPORT 1 von PROD 1 von COMP 1")
                        .ParentNode
                        .AddChild().Name("REPORT 2 von PROD 1 von COMP 1")
                        .ParentNode
                    .ParentNode
                .ParentNode
                .AddChild().Name("COMP 2")
                .ParentNode
                .AddChild().Name("COMP 3")
                    .AddChild().Name("PROD 1 von COMP 3");
            return node;
        }

       
    }

   
}
